# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 11:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('platform', models.PositiveSmallIntegerField(default=0, verbose_name=[(0, 'Stripe')])),
                ('provider', models.PositiveSmallIntegerField(default=0, verbose_name=[(0, 'Card')])),
                ('success', models.BooleanField(default=False)),
                ('request', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='reqeust',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='response',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Payment'),
        ),
    ]
