# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-02 21:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0021_auto_20171202_2148'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('blockchain', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blockchain_tx', models.TextField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comment')),
            ],
            options={
                'verbose_name_plural': 'Topic Snapshots',
                'verbose_name': 'Topic Snapshot',
            },
        ),
        migrations.CreateModel(
            name='ContributionCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(default=0, verbose_name=[(0, 'DOER'), (1, 'INVESTOR')])),
                ('hours', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('matched', models.BooleanField(default=True)),
                ('broken', models.BooleanField(default=False)),
                ('comment_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.CommentSnapshot')),
            ],
            options={
                'verbose_name_plural': 'Contribution Certificates',
                'verbose_name': 'Contribution Certificate',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'verbose_name': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='CurrencyPriceSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('blockchain', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blockchain_tx', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
                ('endpoint', models.TextField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Currency')),
            ],
            options={
                'verbose_name_plural': 'Currency Price Snapshots',
                'verbose_name': 'Currency Price Snapshot',
            },
        ),
        migrations.CreateModel(
            name='HourPriceSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('blockchain', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blockchain_tx', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
                ('endpoint', models.TextField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Currency')),
            ],
            options={
                'verbose_name_plural': 'Hour Price Snapshots',
                'verbose_name': 'Hour Price Snapshot',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('claimed_hours_to_match', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comment')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.CommentSnapshot')),
            ],
            options={
                'verbose_name_plural': 'Interactions',
                'verbose_name': 'Interaction',
            },
        ),
        migrations.CreateModel(
            name='TopicSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('blockchain', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blockchain_tx', models.TextField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Topic')),
            ],
            options={
                'verbose_name_plural': 'Topic Snapshots',
                'verbose_name': 'Topic Snapshot',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('payment_amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('hour_unit_cost', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('donated_hours', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('matched_hours', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comment')),
                ('currency_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.CurrencyPriceSnapshot')),
                ('hour_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.HourPriceSnapshot')),
                ('payment_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Currency')),
                ('payment_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('payment_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.CommentSnapshot')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'verbose_name': 'Transaction',
            },
        ),
        migrations.AddField(
            model_name='contributioncertificate',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Interaction'),
        ),
        migrations.AddField(
            model_name='contributioncertificate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.ContributionCertificate'),
        ),
        migrations.AddField(
            model_name='contributioncertificate',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributioncertificate',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
    ]
