# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20171217_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
