# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_currency_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
