# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20180213_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='will_deduce_reserve_by',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
