# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-03 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_will_deduce_reserve_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='will_deduce_reserve_by',
        ),
    ]
