# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_languagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagename',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
