# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-28 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_languagename_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='one_time_password',
            field=models.CharField(default=25350496, max_length=64),
        ),
    ]
