# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-28 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180628_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='one_time_password',
            field=models.CharField(default=users.models.random_string, max_length=64),
        ),
    ]
