# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-08 16:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171202_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('identifiers', models.TextField()),
                ('domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, size=None)),
            ],
            options={
                'verbose_name': 'Member organization',
                'verbose_name_plural': 'Member organizations',
            },
        ),
    ]
