# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_memberorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('lang', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Language name',
                'verbose_name_plural': 'Language names',
            },
        ),
    ]
