# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171021_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='code_name',
        ),
        migrations.RemoveField(
            model_name='type',
            name='code_number',
        ),
        migrations.RemoveField(
            model_name='type',
            name='data',
        ),
        migrations.RemoveField(
            model_name='type',
            name='data_format_name',
        ),
        migrations.RemoveField(
            model_name='type',
            name='endpoint',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='definition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=[(0, 'Asset'), (1, 'Agent'), (2, 'Place'), (3, 'Event')]),
        ),
    ]
