# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171024_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=[(0, 'Thing'), (1, 'Agent'), (2, 'Place'), (3, 'Event')]),
        ),
    ]
