# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 22:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171031_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='commentsnapshot',
            name='assumed_hours',
        ),
        migrations.RemoveField(
            model_name='commentsnapshot',
            name='claimed_hours',
        ),
        migrations.RemoveField(
            model_name='commentsnapshot',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commentsnapshot',
            name='text',
        ),
        migrations.AddField(
            model_name='commentsnapshot',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
