# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-05 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171031_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsnapshot',
            name='blockchain',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicsnapshot',
            name='blockchain_tx',
            field=models.TextField(blank=True, null=True),
        ),
    ]
