# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171105_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blockchain',
            field=models.PositiveSmallIntegerField(default=False, verbose_name=[(0, 'IPDB')]),
        ),
        migrations.AddField(
            model_name='topic',
            name='blockchain',
            field=models.PositiveSmallIntegerField(default=False, verbose_name=[(0, 'IPDB')]),
        ),
    ]
