# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171112_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='parent_types', to='core.Type'),
        ),
    ]
