# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171127_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='category',
            field=models.BooleanField(default=True),
        ),
    ]
