# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='topic_categories', to='core.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='category',
            field=models.BooleanField(default=False),
        ),
    ]
