# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-28 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171128_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='concept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Type'),
            preserve_default=False,
        ),
    ]
