# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20171202_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-pk',), 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Comment'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
