# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-30 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20171217_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='type',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
