# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-30 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
        ('core', '0025_auto_20171230_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='topic_categories', to='meta.Type'),
        ),
    ]
