# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-08 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_auto_20180201_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='unsubscribed',
            field=models.ManyToManyField(blank=True, related_name='topic_unsubscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
