# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_topic_unsubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
