# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 14:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0004_auto_20180213_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('platform', models.PositiveSmallIntegerField(default=0, verbose_name=[(0, 'Stripe'), (1, 'Braintree'), (2, 'Paypal')])),
                ('provider', models.PositiveSmallIntegerField(default=0, verbose_name=[(0, 'Card'), (1, 'SEPA Direct Debit'), (2, 'Alipay'), (3, 'WeChat'), (4, 'Amex Express Checkout'), (5, 'Giropay'), (6, 'SOFORT')])),
                ('success', models.BooleanField(default=False)),
                ('request', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReserveExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('hours', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('hours', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='transactions.Currency')),
                ('currency_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_prices', to='transactions.CurrencyPriceSnapshot')),
                ('hour_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_prices', to='transactions.HourPriceSnapshot')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
