# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20180213_0021'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveexpense',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.Transaction'),
        ),
    ]
