# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0004_auto_20180213_0021'),
        ('trade', '0002_reserveexpense_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('hours', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='transactions.Currency')),
                ('currency_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_prices', to='transactions.CurrencyPriceSnapshot')),
                ('hour_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_prices', to='transactions.HourPriceSnapshot')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.Payment')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='reserveexpense',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='reserveexpense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservepurchase',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='reservepurchase',
            name='currency_price',
        ),
        migrations.RemoveField(
            model_name='reservepurchase',
            name='hour_price',
        ),
        migrations.RemoveField(
            model_name='reservepurchase',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='reservepurchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReserveExpense',
        ),
        migrations.DeleteModel(
            name='ReservePurchase',
        ),
    ]
