# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-03 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180302_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='currency_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_prices', to='transactions.CurrencyPriceSnapshot'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='hour_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hour_prices', to='transactions.HourPriceSnapshot'),
        ),
    ]
