# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-03 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='owner',
        ),
    ]
