# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-03 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20180303_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='success',
            new_name='paid',
        ),
    ]
