# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-03 18:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20180303_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
