# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-03 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20180303_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.NullBooleanField(default=None),
        ),
    ]
