# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20180305_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.Payment', unique=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.Transaction', unique=True),
        ),
    ]
