# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_auto_20180305_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='platform',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=[(0, 'Testing'), (1, 'Stripe'), (2, 'Braintree'), (3, 'Paypal')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=[(0, 'Test'), (1, 'Card'), (2, 'SEPA Direct Debit'), (3, 'Alipay'), (4, 'WeChat'), (5, 'Amex Express Checkout'), (6, 'Giropay'), (7, 'SOFORT')]),
        ),
    ]
