# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_auto_20180305_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_test',
        ),
        migrations.AddField(
            model_name='reserve',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
    ]
