# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 06:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIXERCurrencyPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FREDHourPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='hourpricesnapshot',
            name='hour_price_currency',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=[(0, 'HUR'), (1, 'EUR'), (2, 'USD'), (3, 'CNY'), (4, 'RUB'), (5, 'JPY'), (6, 'INR')]),
        ),
        migrations.AlterField(
            model_name='hourpricesnapshot',
            name='target_currency',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=[(0, 'HUR'), (1, 'EUR'), (2, 'USD'), (3, 'CNY'), (4, 'RUB'), (5, 'JPY'), (6, 'INR')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_currency',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=[(0, 'HUR'), (1, 'EUR'), (2, 'USD'), (3, 'CNY'), (4, 'RUB'), (5, 'JPY'), (6, 'INR')]),
        ),
        migrations.AddField(
            model_name='fixercurrencyprices',
            name='fred_hour_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FREDHourPrice'),
        ),
    ]
