# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-21 21:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170924_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
