# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-12 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171112_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blockchain',
            field=models.PositiveSmallIntegerField(default=False, verbose_name=[(0, 'None'), (1, 'IPDB')]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='blockchain',
            field=models.PositiveSmallIntegerField(default=False, verbose_name=[(0, 'None'), (1, 'IPDB')]),
        ),
    ]
