# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-28 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20171127_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='role',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=[(0, 'Thing'), (1, 'Agent'), (2, 'Place'), (3, 'Event')]),
        ),
    ]
