# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-28 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_item_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='identifiers',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
