# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-02 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_item_identifiers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Instance',
        ),
        migrations.RemoveField(
            model_name='commentsnapshot',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='contributioncertificate',
            name='comment_snapshot',
        ),
        migrations.RemoveField(
            model_name='contributioncertificate',
            name='interaction',
        ),
        migrations.RemoveField(
            model_name='contributioncertificate',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='contributioncertificate',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='contributioncertificate',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='currencypricesnapshot',
            name='base',
        ),
        migrations.RemoveField(
            model_name='hourpricesnapshot',
            name='base',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='topicsnapshot',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='hour_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_recipient',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_sender',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='snapshot',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'verbose_name': 'Instance', 'verbose_name_plural': 'Instances'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.RenameField(
            model_name='type',
            old_name='category',
            new_name='is_category',
        ),
        migrations.AlterField(
            model_name='type',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CommentSnapshot',
        ),
        migrations.DeleteModel(
            name='ContributionCertificate',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='CurrencyPriceSnapshot',
        ),
        migrations.DeleteModel(
            name='HourPriceSnapshot',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.DeleteModel(
            name='TopicSnapshot',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
