# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 08:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20180107_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='specification',
            new_name='schema_spec',
        ),
        migrations.RenameField(
            model_name='schema',
            old_name='description',
            new_name='version',
        ),
        migrations.AddField(
            model_name='schema',
            name='types_spec',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='schema',
            unique_together=set([('name', 'version')]),
        ),
    ]
