# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_auto_20180127_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
