# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_auto_20180127_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.Type'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together=set([('concept', 'schema', 'identifiers')]),
        ),
    ]
