# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 16:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_instance_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='identifiers',
            field=models.TextField(default='object'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
