# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0009_auto_20180202_1607'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together=set([]),
        ),
    ]
