# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0010_auto_20180202_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
