# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-07 10:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('specification', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('types', models.ManyToManyField(blank=True, related_name='schema_types', to='meta.Type')),
            ],
            options={
                'verbose_name_plural': 'Schemas',
                'verbose_name': 'Schema',
            },
        ),
        migrations.AddField(
            model_name='instance',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.Schema'),
        ),
    ]
